### ISSUE TITLE
Red AWACS Frequencies

### ISSUE THREAD

**Issue by chandawg** [ModernColdWar/Miz-Files#4]
Changed AWACS Frequencies from 151 152 153 155 to 121.5 122.5 123.5 125.5 accommodate specific aircraft.

**Comment by chandawg** [comment]
New MIZ 4.4.9 submitted

**Comment by chandawg** [comment]
I didnt upload this to the server, I uploaded it to github to be placed on the server. Why was I removed from the ModrnColdWar organization?

**Comment by chandawg** [comment]
Rather than kick me out of the group, which I started btw to foster collaboration on miz updates, a comment could have been put here that the process of updating miz files have changed

**Comment by Winston2108** [comment]
Of course, when I have a chance we can do that! Very busy IRL this week which is why everything is "next week" at the minute
